environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
clone_depth: 1
matrix:
  fast_finish: true
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
